# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1024)),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(blank=True, max_length=128, null=True)),
                ('content', models.TextField()),
                ('love_count', models.IntegerField(default=0)),
                ('say_count', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='bbs_pic.jpg', upload_to='bbs_pictrue/')),
                ('view_count', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BBS_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_bbs_id', models.CharField(default=None, max_length=1024)),
                ('signature', models.CharField(default='这个家伙很懒，什么都没留下。', max_length=128)),
                ('photo', models.ImageField(default='/static/upload_img/user_1.jpg', upload_to='upload_img')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.BBS_user')),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.CharField(default='cb', max_length=10)),
                ('key', models.IntegerField(default=0)),
                ('start_time', models.IntegerField(default=0)),
                ('end_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='bbs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.BBS_user'),
        ),
        migrations.AddField(
            model_name='bbs',
            name='bbs_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.Category'),
        ),
    ]
