# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20170620_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_user',
            name='photo',
            field=models.ImageField(default='/static/upload_img/user_1.jpg', upload_to='static/upload_img/'),
        ),
    ]
