# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20170620_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs',
            name='picture',
            field=models.ImageField(default='bbs_pic.jpg', null=True, upload_to='bbs_pictrue/'),
        ),
    ]
