# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20170620_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbs_user',
            name='user_bbs_id',
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
