# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_html',
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=5000000, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
