# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plan_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planName', models.CharField(max_length=255)),
                ('planGuid', models.CharField(max_length=255)),
                ('projectGuid', models.CharField(max_length=255)),
                ('isMail', models.CharField(max_length=255)),
                ('isReport', models.CharField(max_length=255)),
                ('isBeautiful', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('isApp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app1_plan',
            },
        ),
        migrations.CreateModel(
            name='project_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=255)),
                ('projectGuid', models.CharField(max_length=255)),
                ('projectUrl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app1_project',
            },
        ),
        migrations.CreateModel(
            name='turn_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnName', models.CharField(max_length=255)),
                ('turnGuid', models.CharField(max_length=255)),
                ('planGuid', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('tester', models.CharField(max_length=255)),
                ('startTime', models.CharField(max_length=255)),
                ('endTime', models.CharField(max_length=255)),
                ('workHour', models.CharField(max_length=255)),
                ('mark', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'app1_turn',
            },
        ),
    ]
