# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turn_model',
            name='endTime',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='turn_model',
            name='startTime',
            field=models.DateField(max_length=255),
        ),
    ]
